overrides:
  '@yardinternet/brave-frontend-kit': link:../../../../Packages/brave-frontend-kit

publicHoistPattern:
  - prettier
  - stylelint
  - eslint
  - stylelint-config-recommended
  - stylelint-config-idiomatic-order
  - '@babel/preset-react'
