publicHoistPattern:
    - '@babel/preset-react'
    - '@types/*'
    - '@wordpress/*'
    - eslint
    - prettier
    - stylelint
    - stylelint-config-idiomatic-order
    - stylelint-config-recommended
